version: '3.9'

services:
  Mito_Angular_app:
    container_name: Mito_Angular_app
    image: mito-angular_app:1.0.0
    build: C:\Camilo\WorkSpaces\STS4\MediApp\mediapp-fronend\hello-world\
    ports:
      - 4200:4200
    depends_on:
      - Mito_API_app
  Mito_API_app:
    container_name: Mito_API_app
    image: mito-api-app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://Mito_db:5432/MediAppDbDocker
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - Mito_db
  Mito_db:
    container_name: Mito_db
    image: postgres:14
    ports:
     - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: MediAppDbDocker