version: '3.9'
services:
  nginx:
    build:
      context: ./
      dockerfile: Docker.nginx
    container_name: nginx-server
    restart: always
    ports:
      - 8080:80
    volumes:
    - ./html:/usr/share/nginx/html/
volumes:
  html: {}