FROM eclipse-temurin:17-jdk-alpine
#RUN apt-get install -y tzdata
#ENV TZ America/Bogota
RUN mkdir /tmp/app
COPY target/*.jar /tmp/app/appbackend.jar
ENTRYPOINT ["java","-Dspring.profiles.active=Docker","-jar","/tmp/app/appbackend.jar"]
EXPOSE 8080
